# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170409_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='post_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
