# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170413_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='post_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
